spring:
  activemq:
    broker-url: tcp://localhost:61616/ # activemq消息组件的连接主机
    user: admin
    password: admin # 账号密码默认为admin
  jms:
    pub-sub-domain: false # 启用发布订阅模式（默认关闭是点对点模式）
server:
  port: 8067
